
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSockets (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  

  webserver:
    build: 
      dockerfile: ./dockerfile.yaml
      context: ./Webserver
    container_name: web_server
    ports:
      - "5000:5000"
    volumes:
      - ./Webserver:/app
    depends_on:
      - mosquitto
    environment:
      DB_PATH: sqlite:///DB/IOT3_DB.db

